title: Into the Flat World of Lence ...
author: R Primus
email: rp@lence.net
description: > # this means to ignore newlines until "baseurl:"
  Wow - an exciting site description!  Aren't we all the wiser now!

# social links
twitter_username: rprimus
github_username:  rprimus

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
